name: docker-image

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker images
        run: |
          sudo make build-base
          sudo make build-community
      - name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: robol/sharelatex
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Push to Docker Hub
        run: |
          sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          sudo docker push -a robol/sharelatex-base
          sudo docker push -a robol/sharelatex
